// examples/sablier/src/App.svelte

<script lang="ts">
	import context from "./lib/context";
	import Info from "./routes/Info.svelte";
	import Withdraw from "./routes/Withdraw.svelte";
	import NotFound from "./routes/NotFound.svelte";
	import type {ITokenContextData} from "@tokenscript/card-sdk/dist/types";

	let token: ITokenContextData;
	let initialised = false;

	const routingMap = {
		'#info': Info,
		'#withdraw': Withdraw,
	};

	let page;

	function routeChange() {
		page = routingMap[document.location.hash] || NotFound;
	}

	web3.tokens.dataChanged = async (oldTokens, updatedTokens, cardId) => {

		if (initialised)
			return;

		context.setToken(updatedTokens.currentInstance);
		token = updatedTokens.currentInstance;

		initialised = true;

		routeChange();
	};

</script>

<svelte:window on:hashchange={routeChange} />

<div>
	<div id="token-container">
		<svelte:component this={page} />
	</div>
</div>

// static/templates/emptyReact/src/App.tsx
import React, { useState, useEffect, FC } from "react";
import { Info } from "./cards/Info";
import { Mint } from "./cards/Mint";
import { NotFound } from "./cards/NotFound";
import {ITokenContextData} from "@tokenscript/card-sdk/dist/types";

const App: FC = () => {
	// add TokenScript Card views here
	enum CardName {
		Info = "#info",
		Mint = "#mint",
		NotFound = "#notFound",
	}

	const [CurrentPageName, setCurrentPageName] = useState<CardName>(
		CardName.Info
	);
	const [token, setToken] = useState<ITokenContextData>();

	const mapCardName = (card: string | null): CardName => {
		switch (card) {
			case CardName.Info:
				return CardName.Info;
			case CardName.Mint:
				return CardName.Mint;
			default:
				return CardName.NotFound;
		}
	};

	const cardComponents: { [key in CardName]: React.FC } = {
		[CardName.Info]: Info,
		[CardName.Mint]: Mint,
		[CardName.NotFound]: NotFound,
	};

	const CurrentPage = cardComponents[CurrentPageName];

	useEffect(() => {
		const routeChange = () => {
			const card = document.location.hash;
			const mappedCardName = mapCardName(card);
			setCurrentPageName(mappedCardName);
		};

		web3.tokens.dataChanged = (prevTokens, newTokens, id) => {
			setToken(newTokens.currentInstance);
		};

		if (web3.tokens.data.currentInstance) {
			setToken(web3.tokens.data.currentInstance);
		}

		window.addEventListener("hashchange", routeChange);
		routeChange(); // Handle initial load

		return () => {
			window.removeEventListener("hashchange", routeChange);
		};
	}, []);

	return <CurrentPage token={token} />;
};

export default App;
