// static/templates/emptySvelte/src/routes/Info.svelte

<script lang="ts">
	import context from "../lib/context";
	import Loader from "../components/Loader.svelte";

	let token;
	let loading = true;

	context.data.subscribe(async (value) => {
		if (!value.token)
			return;
		token = value.token;
		// You can load other data before hiding the loader
		loading = false;
	});

</script>

<div>
	{#if token}
		<h3>Welcome to TokenScript</h3>
		<p>When a card loads in TokenScript, it gets access to the token context data through TokenScript engine</p>
		<pre>
			${JSON.stringify(token, null, 2)}
		</pre>
	{/if}
	<Loader show={loading}/>
</div>

// static/templates/emptyReact/src/cards/Info.tsx
import React, { useState, useEffect } from "react";
import Loader from "../components/loader/loader";

// @ts-ignore
export const Info: React.FC = ({ token }) => {
	const [loading, setLoading] = useState(true);

	useEffect(() => {
		setLoading(false);
	}, []);

	return (
		<div>
			{token && <pre>{JSON.stringify(token, null, 2)}</pre>}
			<Loader show={loading} />
		</div>
	);
};
