// static/templates/emptySvelte/src/routes/Mint.svelte
<script lang="ts">
	import context from "../lib/context";
	import Loader from "../components/Loader.svelte";

	let token;
	let loading = true;

	context.data.subscribe(async (value) => {
		if (!value.token)
			return;
		token = value.token;
		// You can load other data before hiding the loader
		loading = false;
	});

</script>

<div>
	{#if token}
		<h3>Mint $tst{TOKENSCRIPT_NAME} ...</h3>
		<p>Actions allow you to invoke a smart contract transaction or invoke a Javascript function within the view.</p>
	{/if}
	<Loader show={loading}/>
</div>

// static/templates/emptyReact/src/cards/Mint.tsx
// @ts-nocheck
import React, { useState, useEffect } from "react";
import Loader from "../components/loader/loader";

export const Mint: React.FC = ({ token }) => {
	const [loading, setLoading] = useState(true);

	useEffect(() => {
		setLoading(false);
	}, []);

	return (
		<div>
			{token && (
				<div>
					<h3>Mint...</h3>
					<p>
						Actions allow you to invoke a smart contract transaction
						or invoke a Javascript function within the view.
					</p>
				</div>
			)}
			<Loader show={loading} />
		</div>
	);
};
